name: e_sports_gamerstalca
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^1.4.0
  sqflite: ^2.0.0+4
  path: ^1.9.0
  path_provider: ^2.0.9
  url_launcher: ^6.0.9
  synchronized: ^3.0.0+1
  provider: ^6.1.2
  sqlite3_flutter_libs: ^0.5.0
  shared_preferences: ^2.0.11  
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dcdg: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_picture.png
    - assets/logo.png
    - assets/clock.png
    - assets/games.png
    - assets/mario.png
    - assets/rayman.png
    - assets/starcraft.png
    - assets/pacman.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
