import 'models/juego.dart';
import 'models/rutina.dart';

List<Juego> obtenerJuegos() {
  return [
    Juego(
      id: 1,
      nombre: 'Super Mario',
      descripcion: 'Un juego clásico de plataformas',
      imagenUrl: 'assets/mario.png',
      genero: 'Plataformas',
      ano: 1985,
      desarrollador: 'Nintendo',
      link: 'https://mario.nintendo.com/es/',
      puntuacion: 9.5,
      rutinas: [
        Rutina(
          id: 1,
          nombre: 'Fácil',
          descripcion: 'Una rutina fácil para principiantes',
          objetivo: 'Completar el primer mundo',
          pasos: {'Salta sobre los Goombas': true, 'Recoge los power-ups': false, 'Completa el nivel': false},
          resultadosEsperados: 'Aprender las mecánicas básicas',
          dificultad: 'Fácil',
          puntuacion: 6.0,
          juegoId: 1,
        ),
        Rutina(
          id: 2,
          nombre: 'Media',
          descripcion: 'Una rutina de dificultad media',
          objetivo: 'Completar los primeros 3 mundos',
          pasos: {'Encuentra todas las monedas escondidas': true, 'Evita las trampas': false, 'Derrota a los jefes de cada mundo': false},
          resultadosEsperados: 'Mejorar tus habilidades',
          dificultad: 'Media',
          puntuacion: 7.0,
          juegoId: 1,
        ),
        Rutina(
          id: 3,
          nombre: 'Difícil',
          descripcion: 'Una rutina difícil para expertos',
          objetivo: 'Completar el juego sin morir',
          pasos: {'Memoriza los patrones enemigos': true, 'Usa las habilidades avanzadas de salto': false, 'Completa los niveles en tiempo récord': false},
          resultadosEsperados: 'Convertirte en un maestro del juego',
          dificultad: 'Difícil',
          puntuacion: 8.0,
          juegoId: 1,
        ),
      ],
    ),
    Juego(
      id: 2,
      nombre: 'Rayman',
      descripcion: 'Un juego de plataformas con hermosos gráficos',
      imagenUrl: 'assets/rayman.png',
      genero: 'Plataformas',
      ano: 1995,
      desarrollador: 'Ubisoft',
      link: 'https://www.ubisoft.com/es-es/game/rayman/origins',
      puntuacion: 9.0,
      rutinas: [
        Rutina(
          id: 4,
          nombre: 'Fácil',
          descripcion: 'Una rutina fácil para principiantes',
          objetivo: 'Completar el primer mundo',
          pasos: {'Recoge todos los lums': true, 'Derrota a los enemigos básicos': false, 'Usa las habilidades de salto y puñetazo': false},
          resultadosEsperados: 'Aprender las mecánicas básicas',
          dificultad: 'Fácil',
          puntuacion: 6.0,
          juegoId: 2,
        ),
        Rutina(
          id: 5,
          nombre: 'Media',
          descripcion: 'Una rutina de dificultad media',
          objetivo: 'Completar los primeros 3 mundos',
          pasos: {'Encuentra las jaulas escondidas': true, 'Derrota a los mini-jefes': false, 'Usa las habilidades avanzadas para superar obstáculos': false},
          resultadosEsperados: 'Mejorar tus habilidades',
          dificultad: 'Media',
          puntuacion: 7.0,
          juegoId: 2,
        ),
        Rutina(
          id: 6,
          nombre: 'Difícil',
          descripcion: 'Una rutina difícil para expertos',
          objetivo: 'Completar el juego sin morir',
          pasos: {'Memoriza los patrones enemigos': true, 'Usa las habilidades combinadas para moverte rápido': false, 'Completa los niveles en tiempo récord': false},
          resultadosEsperados: 'Convertirte en un maestro del juego',
          dificultad: 'Difícil',
          puntuacion: 8.0,
          juegoId: 2,
        ),
      ],
    ),
    Juego(
      id: 3,
      nombre: 'Starcraft',
      descripcion: 'Un juego de estrategia en tiempo real en el espacio',
      imagenUrl: 'assets/starcraft.png',
      genero: 'Estrategia en Tiempo Real',
      ano: 1998,
      desarrollador: 'Blizzard Entertainment',
      link: 'https://starcraft2.blizzard.com',
      puntuacion: 9.5,
      rutinas: [
        Rutina(
          id: 7,
          nombre: 'Fácil',
          descripcion: 'Una rutina fácil para principiantes',
          objetivo: 'Ganar la primera campaña',
          pasos: {'Construye una base sólida': true, 'Recolecta recursos': false, 'Entrena unidades básicas': false},
          resultadosEsperados: 'Aprender las mecánicas básicas',
          dificultad: 'Fácil',
          puntuacion: 6.0,
          juegoId: 3,
        ),
        Rutina(
          id: 8,
          nombre: 'Media',
          descripcion: 'Una rutina de dificultad media',
          objetivo: 'Ganar tres campañas',
          pasos: {'Usa estrategias de ataque y defensa': true, 'Investiga tecnologías avanzadas': false, 'Maneja varias bases simultáneamente': false},
          resultadosEsperados: 'Mejorar tus habilidades',
          dificultad: 'Media',
          puntuacion: 7.0,
          juegoId: 3,
        ),
        Rutina(
          id: 9,
          nombre: 'Difícil',
          descripcion: 'Una rutina difícil para expertos',
          objetivo: 'Ganar todas las campañas sin perder unidades clave',
          pasos: {'Usa tácticas avanzadas de microgestión': true, 'Coordina ataques múltiples': false, 'Adapta estrategias según el enemigo': false},
          resultadosEsperados: 'Convertirte en un maestro del juego',
          dificultad: 'Difícil',
          puntuacion: 8.0,
          juegoId: 3,
        ),
      ],
    ),
    Juego(
      id: 4,
      nombre: 'Pacman',
      descripcion: 'Un juego clásico de laberintos',
      imagenUrl: 'assets/pacman.png',
      genero: 'Arcade',
      ano: 1980,
      desarrollador: 'Namco',
      link: 'https://pacman.com/en/',
      puntuacion: 8.5,
      rutinas: [
        Rutina(
          id: 10,
          nombre: 'Fácil',
          descripcion: 'Una rutina fácil para principiantes',
          objetivo: 'Completar el primer nivel',
          pasos: {'Come todos los puntos': true, 'Evita a los fantasmas': false, 'Usa los power pellets estratégicamente': false},
          resultadosEsperados: 'Aprender las mecánicas básicas',
          dificultad: 'Fácil',
          puntuacion: 6.5,
          juegoId: 4,
        ),
        Rutina(
          id: 11,
          nombre: 'Media',
          descripcion: 'Una rutina de dificultad media',
          objetivo: 'Completar los primeros 3 niveles',
          pasos: {'Memoriza los patrones de los fantasmas': true, 'Usa los túneles de manera eficiente': false, 'Maximiza el uso de los power pellets': false},
          resultadosEsperados: 'Mejorar tus habilidades',
          dificultad: 'Media',
          puntuacion: 7.5,
          juegoId: 4,
        ),
        Rutina(
          id: 12,
          nombre: 'Difícil',
          descripcion: 'Una rutina difícil para expertos',
          objetivo: 'Completar el juego sin perder vidas',
          pasos: {'Usa patrones de movimiento óptimos': true, 'Gestiona los power pellets con precisión': false, 'Evita a los fantasmas en niveles avanzados': false},
          resultadosEsperados: 'Convertirte en un maestro del juego',
          dificultad: 'Difícil',
          puntuacion: 8.5,
          juegoId: 4,
        ),
      ],
    ),
  ];
}
